# Generated by Django 4.0.5 on 2022-08-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='mtype',
            field=models.CharField(blank=True, choices=[('RFR', 'Reference Material'), ('PYQ', 'Previous Year Questions'), ('NTS', 'Notes')], max_length=64),
        ),
    ]
